Update bundler dependency
flajann2/juwelier pull request #1
Opened 2016-10-07 13:57 UTC by anero

2016-10-07 13:59 UTC, anero commented
This should resolve #289

2016-10-09 06:31 UTC, zalt50 requested changes
Juwelier itself should be removed from the dependence to prevent "infinite loop"

2016-10-10 14:19 UTC, anero commented
@zalt50 what do you think of 96fecac489514d00fffba5526c8d2b1bb23d6ca1? Was the self dependency only included to allow using juwelier's rake tasks on the gem itself?

2016-10-11 11:22 UTC, zalt50 commented
@anero it works well!

2016-10-13 07:09 UTC, flajann2 commented on Gemfile
> +gem "bundler", ">= 1.13"
I think it should be a bit more general and made 
gem "bundler", ">= 1"
What are your thoughts on this?

2016-10-13 07:11 UTC, flajann2 approved these changes

2016-10-13 07:11 UTC, merged